# Server Port
# server.port=8080 (Configured below)

# Application Name
spring.application.name=finance-app

# Server Port
server.port=8080

# Application Name
spring.application.name=finance-app

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/finance_app

